### ISSUE TITLE
Randomly failing tests

### ISSUE THREAD

**Issue by KevinColemanInc** [danoctavian/algo-challenge-doubly-linked-list#1]
I read your article [https://danoctavian.com/2019/03/25/saving-time-property-based-testing/](https://danoctavian.com/2019/03/25/saving-time-property-based-testing/) and I kinda just want to give my $0.02

Using a random sequence to test a class will be very frustrating to maintain, because when there is a random failure in the future, its going to be difficult to reproduce. I guess you could log the random number generator seed number, but fixing random failures takes a lot of dev time.

When your test case fails, it will say, some operation after N of 1000 iterations did not match up. A dev has no idea which operation failed, what the state the system was before or of the failure.

Maybe you could generate your sequence and store it in a file. During the test, you could load the file, run through the process and then return the current state of the arrays and operation line failed?

**Comment by danoctavian** [comment]
@KevinColemanInc  jsverify shows you the test case that failed if you run it. it does the job of minimizing the input and finding the smallest failing case for you. so you don't need to guess what that was. I think that addresses your concern, but it was something that i did not mention in my article, true, i can add that.

**Comment by danoctavian** [comment]
To give you an example, i deleted line 33 in the DoublyLinkedList file and the random operations test fails with:

  TypeError: Failed after 4 tests and 4 shrinks. rngState: 8542b0f57e9d861ca3; Counterexample: [-128]; [{"op":"push","val":4}, {"op":"pop"}]; Exception: Cannot set property 'next' of null

so it narrows down a minimal failing case for you so you can easily reproduce it saving all that time you mentioned. it uses a strategy to keep reducing the input "size" until it doesn't fail anymore and take the smallest one that failed.

**Comment by KevinColemanInc** [comment]
Awe, so it does log the rngState? That is pretty cool. I wonder how much slower it makes the tests, since it sounds like it re-runs the tests over and over.

**Comment by danoctavian** [comment]
@KevinColemanInc yeah and it prints the counter example so you can just plug it in. what i have here runs really fast, there's no I/O but you may need to bound things once in a while.

**Comment by KevinColemanInc** [comment]
> runs really fast

Lets say you have 5,000 tests with 10,000 length failing arrays. Is it still quick?
